services:
  - type: web
    name: meu_site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn meu_site.wsgi:application --chdir meu_site
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: meu_site.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false