services:
  - type: web
    name: portfolio
    env: python
    buildCommand: |
      cd meu_site
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn meu_site.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: meu_site.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: true